//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyDrop.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyDrop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BACK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChangeLevel {
            get {
                return ResourceManager.GetString("ChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageJapanese {
            get {
                return ResourceManager.GetString("LanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AUTHOR FEED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeAuthorFeed {
            get {
                return ResourceManager.GetString("ModeAuthorFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View a user&apos;s posts while playing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeAuthorFeedDesc {
            get {
                return ResourceManager.GetString("ModeAuthorFeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CREATE POST に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeCreatePost {
            get {
                return ResourceManager.GetString("ModeCreatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write posts using T9 input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeCreatePostDesc {
            get {
                return ResourceManager.GetString("ModeCreatePostDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FEED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeDiscoverFeed {
            get {
                return ResourceManager.GetString("ModeDiscoverFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bluesky feeds and puzzles, together! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeDiscoverFeedDesc {
            get {
                return ResourceManager.GetString("ModeDiscoverFeedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ANTI-SOCIAL MODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeNormal {
            get {
                return ResourceManager.GetString("ModeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No posts, only blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeNormalDesc {
            get {
                return ResourceManager.GetString("ModeNormalDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T9 GENERATOR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeT9Generator {
            get {
                return ResourceManager.GetString("ModeT9Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert text to T9 sequences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeT9GeneratorDesc {
            get {
                return ResourceManager.GetString("ModeT9GeneratorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIMELINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeTimeline {
            get {
                return ResourceManager.GetString("ModeTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your home timeline while playing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModeTimelineDesc {
            get {
                return ResourceManager.GetString("ModeTimelineDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NavLeftRight {
            get {
                return ResourceManager.GetString("NavLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NavSelect {
            get {
                return ResourceManager.GetString("NavSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Navigate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NavUpDown {
            get {
                return ResourceManager.GetString("NavUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLAY に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Requires Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequiresLogin {
            get {
                return ResourceManager.GetString("RequiresLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT LEVEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLevel {
            get {
                return ResourceManager.GetString("SelectLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT MODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeAuto {
            get {
                return ResourceManager.GetString("ThemeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
    }
}
